# ==============================================================================
# PAC DIAGNOSTIC ENGINE (v_mod6)
#
# This is the "champion" engine. It uses the 'messiness_map_v_mod6.json'
# data file, which was generated by 'test-9_mod6-Reside-Analysis.py'.
# ==============================================================================

import json
import math

ENGINE_DATA_FILE = "../data/messiness_map_v_mod6.json"
MESSINESS_MAP_V_MOD6 = None

def load_engine_data():
    """Loads the v_mod6 messiness map from the JSON file."""
    global MESSINESS_MAP_V_MOD6
    try:
        with open(ENGINE_DATA_FILE, 'r') as f:
            data = json.load(f)
            # Convert string keys back to integers
            MESSINESS_MAP_V_MOD6 = {int(k): v for k, v in data.items()}
            return True
    except FileNotFoundError:
        print(f"FATAL ERROR: Engine file '{ENGINE_DATA_FILE}' not found.")
        print("Please run 'test-9_mod6-Reside-Analysis.py' first to create this file.")
        return False
    except Exception as e:
        print(f"FATAL ERROR: Could not load or parse engine file: {e}")
        return False

def get_messiness_score_v_mod6(anchor_sn):
    """The PAC Diagnostic Engine (v_mod6)."""
    if MESSINESS_MAP_V_MOD6 is None:
        return float('inf') 
        
    residue = anchor_sn % 6
    
    # Look up the score (failure rate) from our verified data
    score = MESSINESS_MAP_V_MOD6.get(residue, float('inf'))
    
    return score