# ==============================================================================
# PAC DIAGNOSTIC ENGINE (v3.0)
#
# This engine uses the 'messiness_map_v3_mod210.json' data file,
# which was generated by 'test-8_SAVE_MAP.py'.
#
# The "Messiness Score" is the actual, measured failure rate (%)
# for a given S_n % 210 residue class.
# ==============================================================================

import json
import math

ENGINE_DATA_FILE = "messiness_map_v3_mod210.json"

def load_engine_data():
    """Loads the v3.0 messiness map from the JSON file."""
    try:
        with open(ENGINE_DATA_FILE, 'r') as f:
            # json.load loads the file, keys are strings
            data = json.load(f)
            # Convert string keys back to integers
            return {int(k): v for k, v in data.items()}
    except FileNotFoundError:
        print(f"FATAL ERROR: Engine file '{ENGINE_DATA_FILE}' not found.")
        print("Please run 'test-8_SAVE_MAP.py' first.")
        return None
    except Exception as e:
        print(f"FATAL ERROR: Could not load or parse engine file: {e}")
        return None

# Load the data once when the module is imported
MESSINESS_MAP_V3 = load_engine_data()

def get_messiness_score_v3(anchor_sn):
    """
    The PAC Diagnostic Engine (v3.0).
    Takes a hypothetical S_n anchor and returns its "Messiness Score".
    """
    if MESSINESS_MAP_V3 is None:
        return float('inf') # Engine failed to load

    # Get the residue class for this anchor
    residue = anchor_sn % 210
    
    # Look up the score (failure rate) from our verified data
    # Default to 'inf' if the residue is somehow not in the map
    score = MESSINESS_MAP_V3.get(residue, float('inf'))
    
    return score